-- Renewable editorial queue. Published rounds remain immutable and independent of source votes.
CREATE TABLE duel_candidates (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
 origin text NOT NULL CHECK(origin IN ('editorial','community')),
 source_post_id uuid UNIQUE REFERENCES community_posts(id) ON DELETE SET NULL,
 submitter_uid text REFERENCES profiles(firebase_uid) ON DELETE CASCADE,
 source_version integer,
 snapshot jsonb,
 universe_id text NOT NULL CHECK(universe_id IN ('marvel','dc')),
 category text NOT NULL DEFAULT 'debate' CHECK(category IN ('debate','stories','characters','worlds','adaptations')),
 translations jsonb,
 status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected','withdrawn','published')),
 scheduled_on date,
 published_post_id uuid REFERENCES community_posts(id) ON DELETE SET NULL,
 reason_code text,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now(),
 CHECK(status NOT IN ('approved','published') OR translations IS NOT NULL)
);
CREATE UNIQUE INDEX duel_schedule_unique ON duel_candidates(scheduled_on) WHERE status='approved' AND scheduled_on IS NOT NULL;
CREATE INDEX duel_queue_idx ON duel_candidates(status,scheduled_on,created_at,id);
CREATE INDEX duel_submitter_idx ON duel_candidates(submitter_uid,created_at DESC);
-- Persist content identities even when a source post or account is removed.
CREATE FUNCTION duel_fingerprint(content jsonb) RETURNS text LANGUAGE sql IMMUTABLE STRICT AS $$
 SELECT md5(lower(trim(regexp_replace(content->>'title','[[:space:]]+',' ','g'))) || '|' ||
 least(lower(trim(regexp_replace(content->>'optionA','[[:space:]]+',' ','g'))),lower(trim(regexp_replace(content->>'optionB','[[:space:]]+',' ','g')))) || '|' ||
 greatest(lower(trim(regexp_replace(content->>'optionA','[[:space:]]+',' ','g'))),lower(trim(regexp_replace(content->>'optionB','[[:space:]]+',' ','g')))))
$$;
CREATE TABLE duel_published_content (fingerprint text PRIMARY KEY, published_on date NOT NULL);
INSERT INTO duel_published_content SELECT DISTINCT ON (duel_fingerprint(t.value)) duel_fingerprint(t.value),d.day
 FROM daily_duels d CROSS JOIN LATERAL jsonb_each(d.translations) t ORDER BY duel_fingerprint(t.value),d.day;
CREATE TABLE duel_curation_decisions (
 id uuid PRIMARY KEY,
 candidate_id uuid NOT NULL REFERENCES duel_candidates(id) ON DELETE CASCADE,
 payload_hash text NOT NULL,
 operator text NOT NULL,
 action text NOT NULL,
 reason text NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE daily_duels ADD COLUMN candidate_id uuid REFERENCES duel_candidates(id) ON DELETE SET NULL;

-- Initial reviewed reserve: forty original bilingual discussions, consumed once.
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','marvel','stories','{"pt-BR": {"title": "Qual leitura você indicaria para começar nos heróis urbanos?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Demolidor: O Homem Sem Medo", "optionB": "Ultimate Homem-Aranha"}, "en": {"title": "Which comic would you recommend to start exploring street-level heroes?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Daredevil: The Man Without Fear", "optionB": "Ultimate Spider-Man"}}'::jsonb,'approved',now()+interval '0 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','dc','stories','{"pt-BR": {"title": "Qual porta de entrada para Batman você escolheria?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Batman: Ano Um", "optionB": "Batman: O Longo Dia das Bruxas"}, "en": {"title": "Which Batman starting point would you choose?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Batman: Year One", "optionB": "Batman: The Long Halloween"}}'::jsonb,'approved',now()+interval '1 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','marvel','characters','{"pt-BR": {"title": "Quem daria o melhor conselho antes de uma decisão difícil?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Tia May", "optionB": "Professor Xavier"}, "en": {"title": "Who would give the best advice before a difficult decision?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Aunt May", "optionB": "Professor X"}}'::jsonb,'approved',now()+interval '2 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','dc','characters','{"pt-BR": {"title": "Quem você escolheria para ensinar trabalho em equipe?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Asa Noturna", "optionB": "Mulher-Maravilha"}, "en": {"title": "Who would you choose to teach teamwork?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Nightwing", "optionB": "Wonder Woman"}}'::jsonb,'approved',now()+interval '3 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','marvel','worlds','{"pt-BR": {"title": "Qual cenário merece mais histórias do cotidiano?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Escola dos X-Men", "optionB": "Edifício Baxter"}, "en": {"title": "Which setting deserves more everyday-life stories?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "The X-Men school", "optionB": "The Baxter Building"}}'::jsonb,'approved',now()+interval '4 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','dc','worlds','{"pt-BR": {"title": "Qual lugar você gostaria de conhecer em uma visita guiada?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Fortaleza da Solidão", "optionB": "Batcaverna"}, "en": {"title": "Which place would you like to take a guided tour of?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "The Fortress of Solitude", "optionB": "The Batcave"}}'::jsonb,'approved',now()+interval '5 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','marvel','adaptations','{"pt-BR": {"title": "Que formato combina mais com uma nova história do Demolidor?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Série investigativa", "optionB": "Animação longa-metragem"}, "en": {"title": "Which format best suits a new Daredevil story?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Detective series", "optionB": "Animated feature"}}'::jsonb,'approved',now()+interval '6 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','dc','adaptations','{"pt-BR": {"title": "Que tipo de jogo do Superman você gostaria de jogar?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Resgates em mundo aberto", "optionB": "Aventura narrativa"}, "en": {"title": "What kind of Superman game would you like to play?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Open-world rescues", "optionB": "Story-driven adventure"}}'::jsonb,'approved',now()+interval '7 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','marvel','debate','{"pt-BR": {"title": "Em uma equipe de heróis, o que pesa mais para você?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Confiança entre os membros", "optionB": "Um plano bem definido"}, "en": {"title": "What matters more to you in a hero team?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Trust between members", "optionB": "A clear plan"}}'::jsonb,'approved',now()+interval '8 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','dc','debate','{"pt-BR": {"title": "O que torna um vilão do Batman mais interessante?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "O desafio intelectual", "optionB": "O conflito emocional"}, "en": {"title": "What makes a Batman villain more interesting?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "The intellectual challenge", "optionB": "The emotional conflict"}}'::jsonb,'approved',now()+interval '9 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','marvel','stories','{"pt-BR": {"title": "O que você prefere entre duas grandes sagas?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Uma aventura solo curta", "optionB": "Uma história do cotidiano"}, "en": {"title": "What do you prefer between two major story arcs?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "A short solo adventure", "optionB": "An everyday-life story"}}'::jsonb,'approved',now()+interval '10 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','dc','stories','{"pt-BR": {"title": "Qual clima você prefere em uma história da Liga?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Mistério que reúne a equipe", "optionB": "Exploração de mundos novos"}, "en": {"title": "Which tone do you prefer in a Justice League story?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "A mystery bringing the team together", "optionB": "Exploring new worlds"}}'::jsonb,'approved',now()+interval '11 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','marvel','characters','{"pt-BR": {"title": "Que parceria merecia uma aventura de investigação?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Jessica Jones e Demolidor", "optionB": "Kate Bishop e Ms. Marvel"}, "en": {"title": "Which partnership deserves a detective adventure?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Jessica Jones and Daredevil", "optionB": "Kate Bishop and Ms. Marvel"}}'::jsonb,'approved',now()+interval '12 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','dc','characters','{"pt-BR": {"title": "Quem você convidaria para liderar uma equipe de estreantes?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Batgirl", "optionB": "Cyborg"}, "en": {"title": "Who would you invite to lead a team of newcomers?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Batgirl", "optionB": "Cyborg"}}'::jsonb,'approved',now()+interval '13 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','marvel','worlds','{"pt-BR": {"title": "Que viagem científica você acompanharia?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Exploração com o Quarteto Fantástico", "optionB": "Pesquisa em Wakanda"}, "en": {"title": "Which scientific journey would you follow?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Exploration with the Fantastic Four", "optionB": "Research in Wakanda"}}'::jsonb,'approved',now()+interval '14 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','dc','worlds','{"pt-BR": {"title": "Qual cidade merece uma série de histórias curtas?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Central City", "optionB": "Star City"}, "en": {"title": "Which city deserves a short-story series?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Central City", "optionB": "Star City"}}'::jsonb,'approved',now()+interval '15 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','marvel','adaptations','{"pt-BR": {"title": "Qual equipe você gostaria de ver em um jogo cooperativo?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Quarteto Fantástico", "optionB": "Jovens Vingadores"}, "en": {"title": "Which team would you like in a cooperative game?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Fantastic Four", "optionB": "Young Avengers"}}'::jsonb,'approved',now()+interval '16 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','dc','adaptations','{"pt-BR": {"title": "Qual formato você escolheria para uma aventura da Zatanna?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Animação de mistério", "optionB": "Jogo de enigmas"}, "en": {"title": "Which format would you choose for a Zatanna adventure?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Mystery animation", "optionB": "Puzzle game"}}'::jsonb,'approved',now()+interval '17 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','marvel','debate','{"pt-BR": {"title": "O que faz você continuar uma coleção?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Evolução dos personagens", "optionB": "Criatividade das aventuras"}, "en": {"title": "What makes you keep following a comic series?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Character development", "optionB": "Creative adventures"}}'::jsonb,'approved',now()+interval '18 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','dc','debate','{"pt-BR": {"title": "O que você valoriza mais em uma história do Superman?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Esperança nas pequenas ações", "optionB": "Dilemas de grandes escolhas"}, "en": {"title": "What do you value most in a Superman story?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Hope in small actions", "optionB": "The dilemmas of big choices"}}'::jsonb,'approved',now()+interval '19 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','marvel','stories','{"pt-BR": {"title": "Que tipo de história dos X-Men você leria hoje?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Convivência e diferenças", "optionB": "Missão em território desconhecido"}, "en": {"title": "What kind of X-Men story would you read today?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Living together despite differences", "optionB": "A mission into unknown territory"}}'::jsonb,'approved',now()+interval '20 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','dc','stories','{"pt-BR": {"title": "Qual leitura você levaria para um clube do livro?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Superman: As Quatro Estações", "optionB": "Mulher-Maravilha: Ano Um"}, "en": {"title": "Which comic would you bring to a book club?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Superman for All Seasons", "optionB": "Wonder Woman: Year One"}}'::jsonb,'approved',now()+interval '21 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','marvel','characters','{"pt-BR": {"title": "Quem você gostaria de acompanhar em um dia sem missões?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Peter Parker", "optionB": "Kamala Khan"}, "en": {"title": "Who would you follow on a day without missions?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Peter Parker", "optionB": "Kamala Khan"}}'::jsonb,'approved',now()+interval '22 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','dc','characters','{"pt-BR": {"title": "Que amizade você gostaria de ver mais explorada?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Superman e Jimmy Olsen", "optionB": "Flash e Lanterna Verde"}, "en": {"title": "Which friendship would you like to see explored further?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Superman and Jimmy Olsen", "optionB": "Flash and Green Lantern"}}'::jsonb,'approved',now()+interval '23 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','marvel','worlds','{"pt-BR": {"title": "Onde você ambientaria uma história de suspense?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Estação espacial com os Guardiões", "optionB": "Bairro de Nova York com Jessica Jones"}, "en": {"title": "Where would you set a suspense story?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "A space station with the Guardians", "optionB": "A New York neighborhood with Jessica Jones"}}'::jsonb,'approved',now()+interval '24 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','dc','worlds','{"pt-BR": {"title": "Que lado de Gotham você quer conhecer melhor?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "A vida de seus moradores", "optionB": "A história de seus bairros"}, "en": {"title": "Which side of Gotham would you like to know better?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "The lives of its residents", "optionB": "The history of its neighborhoods"}}'::jsonb,'approved',now()+interval '25 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','marvel','adaptations','{"pt-BR": {"title": "O que você priorizaria em um novo jogo dos X-Men?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Combinar poderes em equipe", "optionB": "Escolhas que afetam relações"}, "en": {"title": "What would you prioritize in a new X-Men game?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Combining powers as a team", "optionB": "Choices that affect relationships"}}'::jsonb,'approved',now()+interval '26 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','dc','adaptations','{"pt-BR": {"title": "Que estilo visual combina com uma nova animação do Batman?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Noir com sombras marcantes", "optionB": "Traço inspirado em HQs"}, "en": {"title": "Which visual style suits a new Batman animation?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Noir with striking shadows", "optionB": "Comic-inspired artwork"}}'::jsonb,'approved',now()+interval '27 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','marvel','debate','{"pt-BR": {"title": "Como você prefere conhecer um herói novo?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Pela própria história de origem", "optionB": "Pelo encontro com outro herói"}, "en": {"title": "How do you prefer to discover a new hero?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Through their origin story", "optionB": "Through a meeting with another hero"}}'::jsonb,'approved',now()+interval '28 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','dc','debate','{"pt-BR": {"title": "Num mistério da Batfamília, o que te prende mais?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Montar as pistas", "optionB": "Entender as motivações"}, "en": {"title": "What draws you into a Bat-family mystery?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Piecing together clues", "optionB": "Understanding motivations"}}'::jsonb,'approved',now()+interval '29 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','marvel','stories','{"pt-BR": {"title": "Que escala você prefere em uma aventura do Thor?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Uma jornada pessoal", "optionB": "Uma saga entre reinos"}, "en": {"title": "What scale do you prefer in a Thor adventure?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "A personal journey", "optionB": "A saga across realms"}}'::jsonb,'approved',now()+interval '30 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','dc','stories','{"pt-BR": {"title": "Qual proposta você escolheria para uma história dos Titãs?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Aprender a liderar", "optionB": "Conciliar amizade e dever"}, "en": {"title": "Which premise would you choose for a Titans story?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Learning to lead", "optionB": "Balancing friendship and duty"}}'::jsonb,'approved',now()+interval '31 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','marvel','characters','{"pt-BR": {"title": "Que dupla renderia uma boa conversa sobre legado?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Steve Rogers e Sam Wilson", "optionB": "Peter Parker e Miles Morales"}, "en": {"title": "Which pair would make for a good conversation about legacy?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Steve Rogers and Sam Wilson", "optionB": "Peter Parker and Miles Morales"}}'::jsonb,'approved',now()+interval '32 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','dc','characters','{"pt-BR": {"title": "Quem merece uma história focada em sua vida civil?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Lois Lane", "optionB": "Renee Montoya"}, "en": {"title": "Who deserves a story focused on their civilian life?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Lois Lane", "optionB": "Renee Montoya"}}'::jsonb,'approved',now()+interval '33 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','marvel','worlds','{"pt-BR": {"title": "Qual ambiente você escolheria para um encontro de leitores?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Uma biblioteca inspirada em Wakanda", "optionB": "Um café inspirado em Nova York"}, "en": {"title": "Which setting would you choose for a readers gathering?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "A Wakanda-inspired library", "optionB": "A New York-inspired café"}}'::jsonb,'approved',now()+interval '34 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','dc','worlds','{"pt-BR": {"title": "Que cenário você exploraria em uma aventura de descoberta?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Themyscira", "optionB": "Atlântida"}, "en": {"title": "Which setting would you explore in a discovery adventure?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Themyscira", "optionB": "Atlantis"}}'::jsonb,'approved',now()+interval '35 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','marvel','adaptations','{"pt-BR": {"title": "Qual gênero combinaria com um jogo da Ms. Marvel?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Aventura com exploração", "optionB": "RPG com relações entre personagens"}, "en": {"title": "Which genre would suit a Ms. Marvel game?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Exploration adventure", "optionB": "RPG with character relationships"}}'::jsonb,'approved',now()+interval '36 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','dc','adaptations','{"pt-BR": {"title": "Que projeto você gostaria de ver com a Canário Negro?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "Série de ação e investigação", "optionB": "Animação com foco na equipe"}, "en": {"title": "Which Black Canary project would you like to see?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "Action and detective series", "optionB": "Team-focused animation"}}'::jsonb,'approved',now()+interval '37 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','marvel','debate','{"pt-BR": {"title": "Para recomendar uma HQ, o que você apresenta primeiro?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "O conflito central", "optionB": "O estilo da arte"}, "en": {"title": "When recommending a comic, what do you introduce first?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "The central conflict", "optionB": "The art style"}}'::jsonb,'approved',now()+interval '38 milliseconds');
INSERT INTO duel_candidates(origin,universe_id,category,translations,status,created_at) VALUES('editorial','dc','debate','{"pt-BR": {"title": "Qual tema rende mais conversa sobre heróis para você?", "text": "Escolha seu lado e conte o motivo. Não há resposta certa: vale a conversa com respeito.", "optionA": "O peso do legado", "optionB": "A construção da confiança"}, "en": {"title": "Which hero theme sparks more conversation for you?", "text": "Pick a side and tell us why. There is no right answer: respectful conversation is what counts.", "optionA": "The weight of legacy", "optionB": "Building trust"}}'::jsonb,'approved',now()+interval '39 milliseconds');
