export const EDITORIAL_UID = 'multiverse-editorial';
const prompts = [
  [
    'marvel',
    'Quem você chamaria para liderar uma missão impossível?',
    'Who would you choose to lead an impossible mission?',
    'Capitão América',
    'Captain America',
    'Homem de Ferro',
    'Iron Man',
  ],
  [
    'dc',
    'Quem rende as melhores histórias de investigação?',
    'Who makes for the best detective stories?',
    'Batman',
    'Batman',
    'Questão',
    'The Question',
  ],
  [
    'marvel',
    'Quem você escolheria para proteger seu bairro?',
    'Who would you choose to protect your neighborhood?',
    'Homem-Aranha',
    'Spider-Man',
    'Demolidor',
    'Daredevil',
  ],
  [
    'dc',
    'Quem seria seu parceiro em uma aventura pelo espaço?',
    'Who would be your partner on a space adventure?',
    'Superman',
    'Superman',
    'Lanterna Verde',
    'Green Lantern',
  ],
  [
    'marvel',
    'Qual equipe você acompanharia em uma nova saga?',
    'Which team would you follow into a new saga?',
    'X-Men',
    'X-Men',
    'Vingadores',
    'Avengers',
  ],
  [
    'dc',
    'Quem você chamaria para salvar uma cidade em crise?',
    'Who would you call to save a city in crisis?',
    'Mulher-Maravilha',
    'Wonder Woman',
    'Flash',
    'The Flash',
  ],
  [
    'marvel',
    'Qual estilo de aventura combina mais com você?',
    'Which adventure style suits you best?',
    'Magia com Doutor Estranho',
    'Magic with Doctor Strange',
    'Tecnologia com Homem de Ferro',
    'Tech with Iron Man',
  ],
  [
    'dc',
    'Que lugar você exploraria primeiro em uma HQ?',
    'Which place would you explore first in a comic?',
    'Gotham',
    'Gotham',
    'Metrópolis',
    'Metropolis',
  ],
  [
    'marvel',
    'Quem merece uma nova grande saga solo?',
    'Who deserves a major new solo saga?',
    'Tempestade',
    'Storm',
    'Feiticeira Escarlate',
    'Scarlet Witch',
  ],
  [
    'dc',
    'Qual dupla você quer ver em uma nova investigação?',
    'Which duo would you like in a new investigation?',
    'Batman e Robin',
    'Batman and Robin',
    'Canário Negro e Arqueiro Verde',
    'Black Canary and Green Arrow',
  ],
  [
    'marvel',
    'Que viagem você encararia com sua equipe?',
    'Which trip would you take with your team?',
    'Wakanda',
    'Wakanda',
    'Asgard',
    'Asgard',
  ],
  [
    'dc',
    'Que equipe você escolheria para uma maratona de leitura?',
    'Which team would you choose for a reading marathon?',
    'Titãs',
    'Titans',
    'Liga da Justiça',
    'Justice League',
  ],
  [
    'marvel',
    'Qual herói rende o melhor debate sobre responsabilidade?',
    'Which hero sparks the best debate about responsibility?',
    'Homem-Aranha',
    'Spider-Man',
    'Pantera Negra',
    'Black Panther',
  ],
  [
    'dc',
    'Quem você escolheria para acolher um novo herói?',
    'Who would you choose to mentor a new hero?',
    'Asa Noturna',
    'Nightwing',
    'Superman',
    'Superman',
  ],
] as const;
export function dailyContent(day: string) {
  const index =
    Math.floor(Date.parse(day + 'T00:00:00Z') / 86400000) % prompts.length;
  const [universe, pt, en, aPT, aEN, bPT, bEN] = prompts[index];
  return {
    universe,
    translations: {
      'pt-BR': {
        title: pt,
        text: 'Duelo do Dia · Curadoria Multiverse. Escolha seu lado e defenda sua ideia com respeito. Não há resposta certa: vale a conversa.',
        optionA: aPT,
        optionB: bPT,
      },
      en: {
        title: en,
        text: 'Daily Duel · Multiverse editorial. Pick a side and make your case respectfully. There is no right answer: the conversation is what counts.',
        optionA: aEN,
        optionB: bEN,
      },
    },
  };
}
