// Identities checked against authenticated TMDB/Metron responses on 2026-10-03.
// Selection is editorial: publisher alone is not a superhero scope filter.
export const tmdbExpansionRegistry = [
  {
    universe: 'dc',
    id: 155,
    title: 'The Dark Knight',
    year: '2008',
    kind: 'movie',
    itemId: 'd-tdk',
  },
  {
    universe: 'dc',
    id: 272,
    title: 'Batman Begins',
    year: '2005',
    kind: 'movie',
    itemId: 'd-tmdb-movie-272',
  },
  {
    universe: 'dc',
    id: 49026,
    title: 'The Dark Knight Rises',
    year: '2012',
    kind: 'movie',
    itemId: 'd-tmdb-movie-49026',
  },
  {
    universe: 'dc',
    id: 268,
    title: 'Batman',
    year: '1989',
    kind: 'movie',
    itemId: 'd-tmdb-movie-268',
  },
  {
    universe: 'dc',
    id: 364,
    title: 'Batman Returns',
    year: '1992',
    kind: 'movie',
    itemId: 'd-tmdb-movie-364',
  },
  {
    universe: 'dc',
    id: 49521,
    title: 'Man of Steel',
    year: '2013',
    kind: 'movie',
    itemId: 'd-tmdb-movie-49521',
  },
  {
    universe: 'dc',
    id: 209112,
    title: 'Batman v Superman: Dawn of Justice',
    year: '2016',
    kind: 'movie',
    itemId: 'd-tmdb-movie-209112',
  },
  {
    universe: 'dc',
    id: 141052,
    title: 'Justice League',
    year: '2017',
    kind: 'movie',
    itemId: 'd-tmdb-movie-141052',
  },
  {
    universe: 'dc',
    id: 791373,
    title: "Zack Snyder's Justice League",
    year: '2021',
    kind: 'movie',
    itemId: 'd-tmdb-movie-791373',
  },
  {
    universe: 'dc',
    id: 297762,
    title: 'Wonder Woman',
    year: '2017',
    kind: 'movie',
    itemId: 'd-tmdb-movie-297762',
  },
  {
    universe: 'dc',
    id: 297802,
    title: 'Aquaman',
    year: '2018',
    kind: 'movie',
    itemId: 'd-tmdb-movie-297802',
  },
  {
    universe: 'dc',
    id: 287947,
    title: 'Shazam!',
    year: '2019',
    kind: 'movie',
    itemId: 'd-tmdb-movie-287947',
  },
  {
    universe: 'dc',
    id: 436969,
    title: 'The Suicide Squad',
    year: '2021',
    kind: 'movie',
    itemId: 'd-tmdb-movie-436969',
  },
  {
    universe: 'dc',
    id: 414906,
    title: 'The Batman',
    year: '2022',
    kind: 'movie',
    itemId: 'd-tmdb-movie-414906',
  },
  {
    universe: 'dc',
    id: 475557,
    title: 'Joker',
    year: '2019',
    kind: 'movie',
    itemId: 'd-tmdb-movie-475557',
  },
  {
    universe: 'dc',
    id: 565770,
    title: 'Blue Beetle',
    year: '2023',
    kind: 'movie',
    itemId: 'd-tmdb-movie-565770',
  },
  {
    universe: 'dc',
    id: 436270,
    title: 'Black Adam',
    year: '2022',
    kind: 'movie',
    itemId: 'd-tmdb-movie-436270',
  },
  {
    universe: 'dc',
    id: 298618,
    title: 'The Flash',
    year: '2023',
    kind: 'movie',
    itemId: 'd-tmdb-movie-298618',
  },
  {
    universe: 'marvel',
    id: 1726,
    title: 'Iron Man',
    year: '2008',
    kind: 'movie',
    itemId: 'm-tmdb-movie-1726',
  },
  {
    universe: 'marvel',
    id: 1724,
    title: 'The Incredible Hulk',
    year: '2008',
    kind: 'movie',
    itemId: 'm-tmdb-movie-1724',
  },
  {
    universe: 'marvel',
    id: 10138,
    title: 'Iron Man 2',
    year: '2010',
    kind: 'movie',
    itemId: 'm-tmdb-movie-10138',
  },
  {
    universe: 'marvel',
    id: 10195,
    title: 'Thor',
    year: '2011',
    kind: 'movie',
    itemId: 'm-tmdb-movie-10195',
  },
  {
    universe: 'marvel',
    id: 1771,
    title: 'Captain America: The First Avenger',
    year: '2011',
    kind: 'movie',
    itemId: 'm-tmdb-movie-1771',
  },
  {
    universe: 'marvel',
    id: 24428,
    title: 'The Avengers',
    year: '2012',
    kind: 'movie',
    itemId: 'm-tmdb-movie-24428',
  },
  {
    universe: 'marvel',
    id: 68721,
    title: 'Iron Man 3',
    year: '2013',
    kind: 'movie',
    itemId: 'm-tmdb-movie-68721',
  },
  {
    universe: 'marvel',
    id: 76338,
    title: 'Thor: The Dark World',
    year: '2013',
    kind: 'movie',
    itemId: 'm-tmdb-movie-76338',
  },
  {
    universe: 'marvel',
    id: 100402,
    title: 'Captain America: The Winter Soldier',
    year: '2014',
    kind: 'movie',
    itemId: 'm-tmdb-movie-100402',
  },
  {
    universe: 'marvel',
    id: 118340,
    title: 'Guardians of the Galaxy',
    year: '2014',
    kind: 'movie',
    itemId: 'm-tmdb-movie-118340',
  },
  {
    universe: 'marvel',
    id: 99861,
    title: 'Avengers: Age of Ultron',
    year: '2015',
    kind: 'movie',
    itemId: 'm-tmdb-movie-99861',
  },
  {
    universe: 'marvel',
    id: 102899,
    title: 'Ant-Man',
    year: '2015',
    kind: 'movie',
    itemId: 'm-tmdb-movie-102899',
  },
  {
    universe: 'marvel',
    id: 271110,
    title: 'Captain America: Civil War',
    year: '2016',
    kind: 'movie',
    itemId: 'm-tmdb-movie-271110',
  },
  {
    universe: 'marvel',
    id: 284052,
    title: 'Doctor Strange',
    year: '2016',
    kind: 'movie',
    itemId: 'm-tmdb-movie-284052',
  },
  {
    universe: 'marvel',
    id: 283995,
    title: 'Guardians of the Galaxy Vol. 2',
    year: '2017',
    kind: 'movie',
    itemId: 'm-tmdb-movie-283995',
  },
  {
    universe: 'marvel',
    id: 315635,
    title: 'Spider-Man: Homecoming',
    year: '2017',
    kind: 'movie',
    itemId: 'm-tmdb-movie-315635',
  },
  {
    universe: 'marvel',
    id: 284053,
    title: 'Thor: Ragnarok',
    year: '2017',
    kind: 'movie',
    itemId: 'm-tmdb-movie-284053',
  },
  {
    universe: 'marvel',
    id: 284054,
    title: 'Black Panther',
    year: '2018',
    kind: 'movie',
    itemId: 'm-tmdb-movie-284054',
  },
  {
    universe: 'marvel',
    id: 299536,
    title: 'Avengers: Infinity War',
    year: '2018',
    kind: 'movie',
    itemId: 'm-tmdb-movie-299536',
  },
  {
    universe: 'marvel',
    id: 363088,
    title: 'Ant-Man and the Wasp',
    year: '2018',
    kind: 'movie',
    itemId: 'm-tmdb-movie-363088',
  },
  {
    universe: 'marvel',
    id: 299537,
    title: 'Captain Marvel',
    year: '2019',
    kind: 'movie',
    itemId: 'm-tmdb-movie-299537',
  },
  {
    universe: 'marvel',
    id: 429617,
    title: 'Spider-Man: Far From Home',
    year: '2019',
    kind: 'movie',
    itemId: 'm-tmdb-movie-429617',
  },
  {
    universe: 'marvel',
    id: 634649,
    title: 'Spider-Man: No Way Home',
    year: '2021',
    kind: 'movie',
    itemId: 'm-tmdb-movie-634649',
  },
  {
    universe: 'marvel',
    id: 566525,
    title: 'Shang-Chi and the Legend of the Ten Rings',
    year: '2021',
    kind: 'movie',
    itemId: 'm-tmdb-movie-566525',
  },
  {
    universe: 'marvel',
    id: 453395,
    title: 'Doctor Strange in the Multiverse of Madness',
    year: '2022',
    kind: 'movie',
    itemId: 'm-tmdb-movie-453395',
  },
  {
    universe: 'marvel',
    id: 505642,
    title: 'Black Panther: Wakanda Forever',
    year: '2022',
    kind: 'movie',
    itemId: 'm-tmdb-movie-505642',
  },
  {
    universe: 'marvel',
    id: 447365,
    title: 'Guardians of the Galaxy Vol. 3',
    year: '2023',
    kind: 'movie',
    itemId: 'm-tmdb-movie-447365',
  },
  {
    universe: 'marvel',
    id: 324857,
    title: 'Spider-Man: Into the Spider-Verse',
    year: '2018',
    kind: 'movie',
    itemId: 'm-tmdb-movie-324857',
  },
  {
    universe: 'dc',
    id: 1412,
    title: 'Arrow',
    year: '2012',
    kind: 'tv',
    itemId: 'd-tmdb-tv-1412',
  },
  {
    universe: 'dc',
    id: 60735,
    title: 'The Flash',
    year: '2014',
    kind: 'tv',
    itemId: 'd-tmdb-tv-60735',
  },
  {
    universe: 'dc',
    id: 95057,
    title: 'Superman & Lois',
    year: '2021',
    kind: 'tv',
    itemId: 'd-tmdb-tv-95057',
  },
  {
    universe: 'dc',
    id: 110492,
    title: 'Peacemaker',
    year: '2022',
    kind: 'tv',
    itemId: 'd-tmdb-tv-110492',
  },
  {
    universe: 'dc',
    id: 194764,
    title: 'The Penguin',
    year: '2024',
    kind: 'tv',
    itemId: 'd-tmdb-tv-194764',
  },
  {
    universe: 'dc',
    id: 2098,
    title: 'Batman: The Animated Series',
    year: '1992',
    kind: 'tv',
    itemId: 'd-tmdb-tv-2098',
  },
  {
    universe: 'marvel',
    id: 85271,
    title: 'WandaVision',
    year: '2021',
    kind: 'tv',
    itemId: 'm-tmdb-tv-85271',
  },
  {
    universe: 'marvel',
    id: 88396,
    title: 'The Falcon and the Winter Soldier',
    year: '2021',
    kind: 'tv',
    itemId: 'm-tmdb-tv-88396',
  },
  {
    universe: 'marvel',
    id: 88329,
    title: 'Hawkeye',
    year: '2021',
    kind: 'tv',
    itemId: 'm-tmdb-tv-88329',
  },
  {
    universe: 'marvel',
    id: 92749,
    title: 'Moon Knight',
    year: '2022',
    kind: 'tv',
    itemId: 'm-tmdb-tv-92749',
  },
  {
    universe: 'marvel',
    id: 61889,
    title: "Marvel's Daredevil",
    year: '2015',
    kind: 'tv',
    itemId: 'm-tmdb-tv-61889',
  },
  {
    universe: 'marvel',
    id: 91363,
    title: 'What If...?',
    year: '2021',
    kind: 'tv',
    itemId: 'm-tmdb-tv-91363',
  },
] as const;

export const metronDCSeriesRegistry = [
  {
    id: 1208,
    titlePT: 'Crise nas Infinitas Terras',
    titleEN: 'Crisis on Infinite Earths',
    year: 1985,
    issues: [
      {
        id: 11518,
        number: '1',
      },
      {
        id: 11519,
        number: '2',
      },
      {
        id: 11520,
        number: '3',
      },
      {
        id: 11521,
        number: '4',
      },
      {
        id: 11522,
        number: '5',
      },
      {
        id: 11523,
        number: '6',
      },
      {
        id: 11524,
        number: '7',
      },
      {
        id: 11525,
        number: '8',
      },
      {
        id: 11526,
        number: '9',
      },
      {
        id: 11527,
        number: '10',
      },
      {
        id: 11528,
        number: '11',
      },
      {
        id: 11529,
        number: '12',
      },
    ],
  },
  {
    id: 537,
    titlePT: 'Watchmen',
    titleEN: 'Watchmen',
    year: 1986,
    issues: [
      {
        id: 4743,
        number: '1',
      },
      {
        id: 4744,
        number: '2',
      },
      {
        id: 4745,
        number: '3',
      },
      {
        id: 4746,
        number: '4',
      },
      {
        id: 4747,
        number: '5',
      },
      {
        id: 4748,
        number: '6',
      },
      {
        id: 4749,
        number: '7',
      },
      {
        id: 4750,
        number: '8',
      },
      {
        id: 4751,
        number: '9',
      },
      {
        id: 4752,
        number: '10',
      },
      {
        id: 4753,
        number: '11',
      },
      {
        id: 4754,
        number: '12',
      },
    ],
  },
  {
    id: 2185,
    titlePT: 'Reino do Amanhã',
    titleEN: 'Kingdom Come',
    year: 1996,
    issues: [
      {
        id: 30503,
        number: '1',
      },
      {
        id: 30504,
        number: '2',
      },
      {
        id: 30505,
        number: '3',
      },
      {
        id: 30506,
        number: '4',
      },
    ],
  },
  {
    id: 2539,
    titlePT: 'Flashpoint',
    titleEN: 'Flashpoint',
    year: 2011,
    issues: [
      {
        id: 36038,
        number: '1',
      },
      {
        id: 36039,
        number: '2',
      },
      {
        id: 36040,
        number: '3',
      },
      {
        id: 36041,
        number: '4',
      },
      {
        id: 36042,
        number: '5',
      },
    ],
  },
  {
    id: 1029,
    titlePT: 'Batman: O Longo Dia das Bruxas',
    titleEN: 'Batman: The Long Halloween',
    year: 1996,
    issues: [
      {
        id: 9075,
        number: '1',
      },
      {
        id: 9076,
        number: '2',
      },
      {
        id: 9077,
        number: '3',
      },
      {
        id: 9078,
        number: '4',
      },
      {
        id: 9079,
        number: '5',
      },
      {
        id: 9080,
        number: '6',
      },
      {
        id: 9081,
        number: '7',
      },
      {
        id: 9082,
        number: '8',
      },
      {
        id: 9083,
        number: '9',
      },
      {
        id: 9084,
        number: '10',
      },
      {
        id: 9085,
        number: '11',
      },
      {
        id: 9086,
        number: '12',
      },
      {
        id: 9087,
        number: '13',
      },
    ],
  },
  {
    id: 6891,
    titlePT: 'Batman: O Cavaleiro das Trevas',
    titleEN: 'Batman: The Dark Knight',
    year: 1986,
    issues: [
      {
        id: 107214,
        number: '1',
      },
      {
        id: 107215,
        number: '2',
      },
      {
        id: 107216,
        number: '3',
      },
      {
        id: 107217,
        number: '4',
      },
    ],
  },
  {
    id: 3988,
    titlePT: 'Grandes Astros: Superman',
    titleEN: 'All Star Superman',
    year: 2006,
    issues: [
      {
        id: 53175,
        number: '1',
      },
      {
        id: 53176,
        number: '2',
      },
      {
        id: 53177,
        number: '3',
      },
      {
        id: 53178,
        number: '4',
      },
      {
        id: 53179,
        number: '5',
      },
      {
        id: 53180,
        number: '6',
      },
      {
        id: 53181,
        number: '7',
      },
      {
        id: 53182,
        number: '8',
      },
      {
        id: 53183,
        number: '9',
      },
      {
        id: 53184,
        number: '10',
      },
      {
        id: 53185,
        number: '11',
      },
      {
        id: 53186,
        number: '12',
      },
    ],
  },
  {
    id: 14273,
    titlePT: 'Watchmen: DC Compact Comics',
    titleEN: 'Watchmen: DC Compact Comics Edition',
    year: 2024,
    issues: [
      {
        id: 158876,
        number: '1',
      },
    ],
    artworkItem: 'd-watchmen',
  },
  {
    id: 7966,
    titlePT: 'Crise nas Infinitas Terras: Edição Absoluta',
    titleEN: 'Crisis on Infinite Earths The Absolute Edition',
    year: 2005,
    issues: [
      {
        id: 123899,
        number: '1',
      },
    ],
    artworkItem: 'd-crise',
  },
] as const;

export const metronDCRegistry = metronDCSeriesRegistry.flatMap((series) =>
  series.issues.map((issue) => ({
    ...issue,
    universe: 'dc' as const,
    seriesID: series.id,
    series: series.titleEN,
    seriesPT: series.titlePT,
    year: series.year,
    itemId:
      'artworkItem' in series
        ? series.artworkItem
        : `d-metron-issue-${issue.id}`,
    artworkOnly: 'artworkItem' in series,
  })),
);
